# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: News
    url: post
    weight: 10
  - name: Über uns
    url: people
    weight: 20
  - name: Events
    url: event
    weight: 30
  - name: Gallerie
    url: gallery
    weight: 40
  - name: Songs
    url: accomplishments
    weight: 50
  - name: Kontakt
    url: contact
    weight: 60
