colorScheme: slate
defaultAppearance: dark
autoSwitchAppearance: false

mainSections:
  - post
  - event

description: "Die Steve Taylor Blues Band aus Koblenz – Blues, Rock und Soul live erleben. Aktuelle Auftrittstermine, Fotos und Infos zur Band."

homepage:
  layout: custom

header:
  layout: basic

navigation:
  showLogo: false
  showTitle: true
  showSearch: true

footer:
  showCopyright: true
  showThemeAttribution: false
  showScrollToTop: true

article:
  showDate: true
  showDateUpdated: false
  showAuthor: false
  showReadingTime: false
  showTableOfContents: false
  showTaxonomies: true
  showWordCount: false
  showSummary: true

list:
  showSummary: true
  groupByYear: false

fathomAnalytics:
  site: ""
